[project]
name = "chronocommits"
version = "0.1.0"
description = "Time-manipulating commits for fake GitHub activity."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=14.0.0",
]
